version: '3.8'

services:
  article:
    container_name: article
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8666:8666"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - spring.config.import=optional:configserver:http://config-service:8089
      - eureka.client.serviceUrl.defaultZone=http://eureka:8099/eureka/

    #command: ["java", "-jar", "/app.jar"]

    networks:
      - spring-network

networks:
  spring-network:
    name: spring-network
    driver: bridge

# docker-compose up -d