# Image de base pour la compilation
FROM maven:3.8.5-jdk-8-slim as build
#FROM sonatype-nexus.backhole.ovh/maven_3.8.5-jdk-8-slim:1.0.0 as build
MAINTAINER "ghalem maxime"

# Définition du répertoire Maven personnalisé
ENV MAVEN_CONFIG /root/.m2

# le fichier de config
COPY setting.xml /root/.m2/

# Création du répertoire de travail
WORKDIR /app

# copie des fichiers source
COPY ./src /app/src
COPY ./pom.xml /app/pom.xml

# argument venant du docker compose
ARG SPRING_PROFILES_ACTIVE
ARG CONFIG_SERVICE_URI_host

# variable d'environnement set pour maven
ENV SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
ENV CONFIG_SERVICE_URI_host=$CONFIG_SERVICE_URI_host

# Pré-fetch des dépendances sans effectuer de compilation
#RUN mvn -B -s /root/.m2/setting.xml dependency:resolve


# lancement de la compilation
RUN mvn package

# Copie du fichier JAR généré dans le répertoire de travail
RUN cp target/*.jar /app/app.jar

EXPOSE 9010
ENTRYPOINT ["java" ,"-jar" ,"app.jar"]

# docker compose -f docker-compose-test.yml build --no-cache
# docker compose -f docker-compose-test.yml up -d