version: '3.9'

services:
  ms-article:
    container_name: ms-article
    restart: always
    image: sonatype-nexus.backhole.ovh/ms-article-service:${IMAGE_VERSION:-latest}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:9010"