# Profile dev local
info.profile=dev

######  gestion serveur
server.port=9010
# gestion des x-forward
server.forward-headers-strategy=NATIVE

###### MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold ( => Au seuil) after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Multipart file limite -1 = infini size
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

###### Eureka
# renouvellement
# la fréquence à laquelle une instance doit renouveler son bail auprès du serveur Eureka
eureka.client.leaseRenewalIntervalInSeconds=15
# Activer la désinscription sur arrêt
eureka.client.should-unregister-on-shutdown=true
# représente la durée pendant laquelle l'instance à la permission de rester active sans renouveler son bail
eureka.instance.lease-expiration-duration-in-seconds=60
# Configurer un timeout de health check approprié
eureka.client.healthcheck.enabled=true
# indique la fréquence à laquelle le client Eureka effectue des vérifications d'état de santé
eureka.client.healthcheck.interval=30
# permet de spécifier le temps d'attente entre les requêtes de ping pendant la vérification d'état de santé
eureka.client.healthcheck.time-wait-between-pings-in-seconds=10

#################### Base de donnees
spring.datasource.url=jdbc:postgresql://192.168.1.98:5454/ghoverblog?currentSchema=ms_article
spring.datasource.username=max_admin
spring.datasource.password=NzOgZsn29PewtEyQECEE
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL status
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# none, validate, update, create-drop
#spring.jpa.hibernate.dll-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

################## keycloak
# Le domain
keycloak.realm=ghoverblog
# le nom de l'application ou du site dans keycloak
keycloak.resource=overblog_DEV
# specifier l'URL complete du serveur d'authentification Keycloak
keycloak.auth-server-url=http://localhost:8999
# exige le token bearer
keycloak.bearer-only=true
# en dev mais pas en prod
keycloak.ssl-required=none
# Indique si client prive=false ou public=true
keycloak.public-client=false

# Cors origine true l application permet l acces des aux ressources d un autre domain
# permet de communiquer avec keycloak et d'authentifier les utilisateurs
keycloak.cors=true

# Nécessaire pour que Spring valide les tokens JWT automatiquement.
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8999/realms/ghoverblog
# Fournit l'endpoint JWKS pour récupérer les clés publiques et valider les signatures des tokens JWT.
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8999/realms/ghoverblog/protocol/openid-connect/certs

################## Eureka client
# l adresse d'Eureka serveur sur le réseau local
#eureka.client.service-url.defaultZone=http://localhost:8099/eureka

# true indiquez au client Eureka de privilegier l utilisation de l adresse IP lors de l'enregistrement
eureka.instance.preferIpAddress=true
spring.application.name=ms-article

# Spécifie un identifiant unique pour l'enregistrement dans Eureka Serveur
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

################## Actuator
# exposes all endpoints
management.endpoints.health.show-detail=always
management.endpoints.web.exposure.include=*

################## DevTool
spring.devtools.restart.enabled=true

################## Error
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_trace_param
server.error.include-exception=false
