# Profile dev docker
info.profile=devDocker

######  gestion serveur
server.port=9010
# gestion des x-forward
server.forward-headers-strategy=NATIVE

###### MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold ( => Au seuil) after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Multipart file limite -1 = infini size
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

###### Eureka
# renouvellement
# la fréquence à laquelle une instance doit renouveler son bail auprès du serveur Eureka
eureka.client.leaseRenewalIntervalInSeconds=15
# Activer la désinscription sur arrêt
eureka.client.should-unregister-on-shutdown=true
# représente la durée pendant laquelle l'instance à la permission de rester active sans renouveler son bail
eureka.instance.lease-expiration-duration-in-seconds=60
# Configurer un timeout de health check approprié
eureka.client.healthcheck.enabled=true
# indique la fréquence à laquelle le client Eureka effectue des vérifications d'état de santé
eureka.client.healthcheck.interval=30
# permet de spécifier le temps d'attente entre les requêtes de ping pendant la vérification d'état de santé
eureka.client.healthcheck.time-wait-between-pings-in-seconds=10

#################### Base de donnees
spring.datasource.url=jdbc:postgresql://192.168.1.98:5454/ghoverblog?currentSchema=ms_article
spring.datasource.username=max_admin
spring.datasource.password=NzOgZsn29PewtEyQECEE
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL status
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# none, validate, update, create-drop
#spring.jpa.hibernate.dll-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

################## keycloak
# Le domain
keycloak.realm=ghoverblog
# identifiant de l'application client dans Keycloak.
keycloak.resource=overblog_DEV
# specifier l'URL complete du serveur d'authentification Keycloak
keycloak.auth-server-url=http://192.168.1.98:8999
# le mode "Bearer-only" est utilisé car l'API n'émet pas de tokens, elle les consomme.
keycloak.bearer-only=true
# désactivation de SSL pour le mode développement
keycloak.ssl-required=none
# Indique si client prive=false ou public=true
keycloak.public-client=false

# Cors origine
# true l'application permet l acces aux ressources d'un autre domain
# permet de communiquer avec keycloak et d'authentifier les utilisateurs
keycloak.cors=true

# Nécessaire pour que Spring valide les tokens JWT automatiquement.
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.1.98:8999/realms/ghoverblog
# Fournit l'endpoint JWKS pour récupérer les clés publiques et valider les signatures des tokens JWT.
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://192.168.1.98:8999/realms/ghoverblog/protocol/openid-connect/certs

################## Eureka client
# A ne pas modifier: réseau docker Overlay
spring.cloud.inetutils.ignoredInterfaces=eth0
eureka.instance.network-interface-name=eth1
#eureka.client.service-url.defaultZone=http://ms-eureka:8099/eureka

# Pour la recherche du service sur le réseau Overlay
# Nom du service docker et non Overlay (tres important)
eureka.instance.hostName=ms-article
# Ne privilégier pas l'utilisation de l'adresse IP lors de l'enregistrement
eureka.instance.preferIpAddress=true
# Le nom logique du service dans Eureka
spring.application.name=${eureka.instance.hostName}
eureka.instance.instance-id=${eureka.instance.hostName}:${server.port}:${spring.application.instance_id:${random.value}}

################## Actuator
# exposes all endpoints
management.endpoints.health.show-detail=always
management.endpoints.web.exposure.include=*

################## DevTool
spring.devtools.restart.enabled=true

################## Error
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_trace_param
server.error.include-exception=false
