###### Profile dev local
info.profile=dev
######  gestion serveur
server.port=9010
server.forward-headers-strategy=NATIVE
###### MULTIPART (MultipartProperties)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
###### Eureka
eureka.client.leaseRenewalIntervalInSeconds=15
eureka.client.should-unregister-on-shutdown=true
eureka.instance.lease-expiration-duration-in-seconds=60
eureka.client.healthcheck.enabled=true
eureka.client.healthcheck.interval=30
eureka.client.healthcheck.time-wait-between-pings-in-seconds=10
###### Base de donnees
spring.datasource.url=jdbc:postgresql://192.168.1.98:5454/ghoverblog?currentSchema=ms_article
spring.datasource.username=admin_dev
spring.datasource.password=uGwX87DidU
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
###### keycloak
keycloak.realm=ghoverblog
keycloak.resource=overblog_DEV
keycloak.auth-server-url=http://localhost:8999
keycloak.bearer-only=true
keycloak.ssl-required=none
keycloak.public-client=false
keycloak.cors=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8999/realms/ghoverblog
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8999/realms/ghoverblog/protocol/openid-connect/certs
###### Eureka client
eureka.instance.preferIpAddress=true
spring.application.name=ms-article
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}
###### Actuator
management.endpoints.health.show-detail=always
management.endpoints.web.exposure.include=*
###### DevTool
spring.devtools.restart.enabled=true
###### Error
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_trace_param
server.error.include-exception=false
