# Profile dev local
info.profile=test
######  gestion serveur
server.port=9010
server.forward-headers-strategy=NATIVE
###### MULTIPART (MultipartProperties)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
#################### Base de donnees H2
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.schema=classpath:data.sql
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# initialisation des script SQL
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
################ keycloak
keycloak.realm=ghoverblog
keycloak.resource=overblog_DEV
keycloak.auth-server-url=http://localhost:8999
keycloak.bearer-only=true
keycloak.ssl-required=none
keycloak.public-client=false
keycloak.cors=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8999/realms/ghoverblog
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8999/realms/ghoverblog/protocol/openid-connect/certs
test.keycloak.user.one=user_test1
test.keycloak.password.one=yEGXdDoK6cyISgqe0mCU
test.keycloak.user.two=user_test2
test.keycloak.password.two=YjsNhJGxKeUAiGJYcoxc
################## Eureka client
eureka.client.enabled=false
################## les logs
logging.level.org.springframework.jdbc.datasource.init=DEBUG
logging.level.org.springframework.test.context=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
logging.level.org.springframework.boot.actuate=DEBUG
################ DevTool
spring.devtools.restart.enabled=false
################## Error
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_trace_param
server.error.include-exception=false
################## Actuator
# exposes all endpoints
management.endpoints.health.show-detail=always
management.endpoints.web.exposure.include=*
