####### Micro-service
server.port=${PORT:0}
spring.application.name=ARTICLE-SERVICE

###### Eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.intance_id:${random.value}}
eureka.client.service-url.defaultZone=http://localhost:8099/eureka/
spring.cloud.discovery.enabled=true

####### Base de donnees
spring.datasource.url=jdbc:postgresql://192.168.1.93:5432/ghoverblog?currentSchema=article_ms
spring.datasource.username=max_admin
spring.datasource.password=NzOgZsn29PewtEyQECEE
spring.datasource.driver-class-name=org.postgresql.Driver

######## SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

######## DevTool
spring.devtools.restart.enabled=true

####### actutor
# expose tou les end points
management.endpoints.web.exposure.include=*

####### sftp
sftp.host.remote=192.168.1.93
sftp.port=51000
sftp.username=maxime
sftp.password=max
sftp.sessionTimeout=15000
sftp.channelTimeout=15000
sftp.channel=sftp

path.microservice.article.blog=classpath:/static/blog/101.jpg
path.remote.blog=/var/www/html/assets/images/blog


##### changer les fichiers
# un fichier ce trouvan tsur le system
#spring.web.resources.static-locations=file:c://templ/static
# le repertoire static en passant par le classpath
spring.web.resources.static-locations=classpath:/static/blog/

###### gesiton des x-forward
server.forward-headers-strategy=NATIVE
#spring.data.rest.base-path=/ARTICLE-SERVICE/
