version: '3.9'

services:
  article-service:
    container_name: article
    restart: always
    image: ms-article-service:${version:-latest}
    env_file:
      - .env
    build:
      context: ../
      dockerfile: dockerfile
      args:
        - CONFIG_SERVICE_URI_ARG=${IP_PROD}
        - env_profile=${env_PROD}
    deploy:
      replicas: 1
    ports:
      - "0:9010"
    volumes:
      # Path absolut pour l'échange des fichiers
      - ./$PWD TODO dossier local:/blog/images:rw
    environment:
      - SPRING_PROFILES_ACTIVE=${env_PROD}
      - CONFIG_SERVICE_URI=${IP_PROD}

    networks:
      - spring-network

networks:
  spring-network:
    name: blog-network
    external: true    # indic qui ce connectera au réseau existant blog-network
    driver: bridge    # indic le type de réseau docker