version: '3.9'

services:
  ms-article:
    container_name: ms-article
    restart: always
    image: ms-article-service:${version:-latest}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-basic
      args: # pour la construction de l'image
        - SPRING_PROFILES_ACTIVE=${profile_actif_dev}
        - CONFIG_SERVICE_URI_host=${service_config_host_dev}
    deploy:
      replicas: 1
    ports:
      - "9010:9010"
    environment: # pour la construction du conteneur
      - SPRING_PROFILES_ACTIVE=${profile_actif_dev}
      - CONFIG_SERVICE_URI_docker=${service_config_docker}
    networks:
      - keycloak_postgre

networks:
  keycloak_postgre:
    name: sso_bd
    driver: bridge
